# Generated by Django 6.0.7 on 2026-08-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_alter_voucher_budget_alter_voucher_value'),
        ('base', '0066_page_text_markdown_to_html'),
    ]

    operations = [
    ]
