# Generated by Django 6.0.7 on 2026-08-27 22:45

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_user_profile_picture_user_profile_picture_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='This is the maximum monetary amount that will be discounted using this voucher across all usages. If this is sum reached, the voucher can no longer be used.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Maximum discount budget'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Voucher value'),
        ),
        migrations.AlterField(
            model_name='invoicevoucher',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='This is the maximum monetary amount that will be discounted using this voucher across all usages.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Maximum discount budget'),
        ),
        migrations.AlterField(
            model_name='invoicevoucher',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Voucher value'),
        ),
    ]
